//
//  Endpoints.swift
//
//  Created by Shahrukh on 1/12/20.
//  Copyright © 2020 Shahrukh. All rights reserved.
//


let LOGIN_API   =   "login"
let SOCIAL_LOGIN = "social/login"
let SOCIAL_REGISTER = "social/register"
let REGISTER = "register"
let LOGOUT_API   =   "logout?deviceId="
let FORGOT_PASSWORD_API   =  "forgot/password"
let CHANGE_PASSWORD_API   =  "change/password"
let SEND_VERIFICATION_EMAIL_API   =  "email/resend"
let QUESTION_API  =  "question/preferences"
let COUNTRY_API = "countries"
let USER_API = "user"
let SPECIALITY = "speciality"
let ALREDY_VERIFIED_EMAIL   =  "email/verification/status"
let HOME    =   "home"
let PSYCHOLOGIST_API = "psychologist"
let PSYCHOLOGIST_DETAIL_ADD_API = "psychologist/details"
let PSYCHOLOGIST_DETAIL = "psychologist/"
let PSYCHOLOGIST_SESSION_AVAILABILITY = "psychologist/session/availability"
let PSYCHOLOGIST_SESSION = "psychologist/sessions"
let PSYCHOLOGIST_APPOINTMENT = "psychologist/appointment"
let PSYCHOLOGIST_PAID_APPOINTMENT = "book/initial/paid/session"
let CHECK_SESSION_AVAILBLITY =  "session/status?version=v2"
let LANGUAGES = "languages"
let ONLYLANGUAGES = "languages"
/* Psychologists services */
let PSYCHOLOGIST_HOME = "psychologist/home"
let GET_STATUS = "profile/status"
let GET_APPOINTMENT = "appointments/"
let GET_APPOINTMENT_DETAIL = "user/session/"
let UPDATE_SESSION = "psychologist/update/session"
let BLOGS = "blogs"
let REVIEW = "review"
let FREE_SESSION_REQUEST = "request/session/"
let CANCEL_REQUEST = "cancel/request/"
let GET_REQUEST_LIST = "session/requests/"
let BLOGS_DETAIL = "blog/"
let CREATE_ROOM = "twilio/create/room/"
let JOIN_ROOM   = "twilio/join/room/"
let END_CALL    =  "twilio/end/call/"
let REGISTER_FOR_PUSH = "register/push/token"
let CANCEL_APPOINTMENT = "cancel/appointment/"
let RESCHEDULE_APPOINTMENT = "reschedule/appointment/"
let PSYCHOLOGIST_WEEKLY_SESSION = "psychologist/weekly/sessions"
let MESSAGE_API = "messages"
let CHAT_LIST   = "chatlist"
let GET_NOTIFICATION_API    = "notifications"
let GET_INFORMATION = "profile/info"
let SETTINGS = "settings"
let SEND_MESSAGE = "send/attachment"
let MONTHLY_SLOTS_AVAILBLITY = "monthly/slots/availability"
let QUESTIONS = "questions"
let CHECK_UPDATE = "check/update"
